# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mining', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descrition', models.CharField(max_length=1200)),
                ('CaCO3', models.CharField(max_length=20)),
                ('CaO', models.CharField(max_length=20)),
                ('Fe2O3', models.CharField(max_length=20)),
                ('MgO', models.CharField(max_length=20)),
                ('Al2O3', models.CharField(max_length=20)),
                ('SiO2', models.CharField(max_length=20)),
                ('loi', models.CharField(max_length=20)),
                ('grainsize', models.CharField(max_length=1200)),
                ('Density', models.CharField(max_length=20)),
                ('Refractive', models.CharField(max_length=20)),
                ('pHvalue', models.CharField(max_length=20)),
                ('Bulkdensity', models.CharField(max_length=20)),
                ('Hardness', models.CharField(max_length=20)),
                ('Moisture', models.CharField(max_length=20)),
            ],
        ),
    ]
