# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mining', '0003_product_mdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Al2O3',
            new_name='al2O3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Bulkdensity',
            new_name='bulkdensity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Density',
            new_name='density',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Fe2O3',
            new_name='fe2O3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Hardness',
            new_name='hardness',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='MgO',
            new_name='mgO',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Moisture',
            new_name='moisture',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Refractive',
            new_name='refractive',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='SiO2',
            new_name='siO2',
        ),
    ]
