# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mining', '0004_auto_20161126_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='CaCO3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='CaO',
        ),
        migrations.RemoveField(
            model_name='product',
            name='al2O3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fe2O3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='loi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mdate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mgO',
        ),
        migrations.RemoveField(
            model_name='product',
            name='siO2',
        ),
    ]
