# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Mining', '0005_auto_20161126_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pHvalue',
            new_name='SiO2',
        ),
        migrations.AddField(
            model_name='product',
            name='al2O3',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='caO',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='cacO3',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='fe2O3',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='loi',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='mgO',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='phvalue',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
